services:
  - type: web
    name: medical-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run medibot.py --server.port=10000 --server.address=0.0.0.0
    envVars:
      - key: HUGGINGFACEHUB_API_TOKEN
        sync: false
